//! Deterministic archive fixture used by the logbook verification scene.

use super::Game;
use crate::engine::RiskOutcome;
use crate::state::{VoyageRecord, WorkspaceScanProfile};

pub(super) fn prepare(game: &mut Game) {
    game.session.voyage_log = records();
    game.voyage_archive_open = true;
}

fn records() -> Vec<VoyageRecord> {
    vec![
        VoyageRecord {
            site_id: "merchant_wreck".to_owned(),
            recovered_count: 2,
            recovered_value: 250,
            recovered_alloy: 5,
            recovered_electronics: 2,
            external_load: 1,
            risk_outcome: RiskOutcome::OrdinaryReturn,
            danger_score: 15,
            reconnaissance_level: 0,
            voyage_plan: crate::engine::VoyagePlan::Cautious,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: true,
            contract_failed: false,
            scan_profile: WorkspaceScanProfile::Standard,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 74,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 0,
            insured: false,
            insurance_premium: 0,
            insurance_payout: 0,
        },
        VoyageRecord {
            site_id: "military_wreck".to_owned(),
            recovered_count: 1,
            recovered_value: 520,
            recovered_alloy: 5,
            recovered_electronics: 6,
            external_load: 2,
            risk_outcome: RiskOutcome::DamagedModule,
            danger_score: 45,
            reconnaissance_level: 1,
            voyage_plan: crate::engine::VoyagePlan::Expedited,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: false,
            contract_failed: false,
            scan_profile: WorkspaceScanProfile::Array,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 48,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 1,
            insured: false,
            insurance_premium: 0,
            insurance_payout: 0,
        },
        VoyageRecord {
            site_id: "research_vessel".to_owned(),
            recovered_count: 3,
            recovered_value: 1_180,
            recovered_alloy: 3,
            recovered_electronics: 17,
            external_load: 1,
            risk_outcome: RiskOutcome::OrdinaryReturn,
            danger_score: 70,
            reconnaissance_level: 2,
            voyage_plan: crate::engine::VoyagePlan::Standard,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: true,
            contract_failed: false,
            scan_profile: WorkspaceScanProfile::Array,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 68,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 2,
            insured: false,
            insurance_premium: 0,
            insurance_payout: 0,
        },
        VoyageRecord {
            site_id: "merchant_wreck".to_owned(),
            recovered_count: 1,
            recovered_value: 160,
            recovered_alloy: 2,
            recovered_electronics: 3,
            external_load: 0,
            risk_outcome: RiskOutcome::LostSalvage,
            danger_score: 15,
            reconnaissance_level: 0,
            voyage_plan: crate::engine::VoyagePlan::Expedited,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: false,
            contract_failed: true,
            scan_profile: WorkspaceScanProfile::Standard,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 60,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 3,
            insured: false,
            insurance_premium: 0,
            insurance_payout: 0,
        },
        VoyageRecord {
            site_id: "military_wreck".to_owned(),
            recovered_count: 2,
            recovered_value: 700,
            recovered_alloy: 9,
            recovered_electronics: 8,
            external_load: 3,
            risk_outcome: RiskOutcome::OrdinaryReturn,
            danger_score: 45,
            reconnaissance_level: 1,
            voyage_plan: crate::engine::VoyagePlan::Standard,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: true,
            contract_failed: false,
            scan_profile: WorkspaceScanProfile::Array,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 42,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 4,
            insured: false,
            insurance_premium: 0,
            insurance_payout: 0,
        },
        VoyageRecord {
            site_id: "research_vessel".to_owned(),
            recovered_count: 1,
            recovered_value: 420,
            recovered_alloy: 2,
            recovered_electronics: 7,
            external_load: 1,
            risk_outcome: RiskOutcome::EmergencyRepair,
            danger_score: 70,
            reconnaissance_level: 2,
            voyage_plan: crate::engine::VoyagePlan::Expedited,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: false,
            contract_failed: false,
            scan_profile: WorkspaceScanProfile::Standard,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 51,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 5,
            insured: true,
            insurance_premium: 175,
            insurance_payout: 120,
        },
        VoyageRecord {
            site_id: "merchant_wreck".to_owned(),
            recovered_count: 2,
            recovered_value: 330,
            recovered_alloy: 6,
            recovered_electronics: 3,
            external_load: 1,
            risk_outcome: RiskOutcome::OrdinaryReturn,
            danger_score: 15,
            reconnaissance_level: 1,
            voyage_plan: crate::engine::VoyagePlan::Cautious,
            return_policy: crate::state::ReturnPolicy::default(),
            contract_completed: true,
            contract_failed: false,
            scan_profile: WorkspaceScanProfile::Array,
            drone_directive: crate::state::DroneDirective::PullSupport,
            condition_after: 53,
            cleared_sections: Vec::new(),
            clearance_payout: 0,
            return_fuel: 2,
            market_cycle: 6,
            insured: false,
            insurance_premium: 0,
            insurance_payout: 0,
        },
    ]
}
